Repository co-niverse/dangjang-backend, pull requests merged in 2023-11, with the labels that each got.

#79 hotfix 로그 버전 숫자 1자리만 허용되는 문제 수정
  src/main/java/com/coniverse/dangjang/domain/log/dto/request/LogRequest.java
Labels: bug

#80 [Hotfix]: v1.3.2 version api dto 정규식 수정
  src/main/java/com/coniverse/dangjang/domain/version/dto/request/VersionRequest.java
Labels: bug

#82 포인트 상품 목록 조회 불가
  src/main/java/com/coniverse/dangjang/domain/point/service/PointService.java
  src/test/java/com/coniverse/dangjang/domain/point/service/PointHistoryServiceTest.java
Labels: refactoring

#83 [Release] v1.5.0 포인트 상품 구매 서비스 마감
  src/main/java/com/coniverse/dangjang/domain/point/service/PointService.java
  src/test/java/com/coniverse/dangjang/domain/point/service/PointHistoryServiceTest.java
Labels: release

#85 알림 메세지 수정
  src/main/java/com/coniverse/dangjang/domain/notification/service/NotificationService.java
  src/test/java/com/coniverse/dangjang/domain/notification/service/NotificationServiceTest.java
Labels: refactoring

#87 운동,체중 가이드 중복 처리
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/document/ExerciseGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/service/WeightGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/point/service/PointService.java
Labels: refactoring
