Repository co-niverse/dangjang-backend, pull requests merged in 2023-08, with the labels that each got.

#26 Embedded MongoDB Config
  build.gradle
  src/test/java/com/coniverse/dangjang/support/annotation/MongoRepositoryTest.java
  src/test/resources/config/application.yml
Labels: test, setting

#27 User medicine,injection 추가 & 닉네임 조건 변경
  src/main/java/com/coniverse/dangjang/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/coniverse/dangjang/domain/user/entity/User.java
  src/main/java/com/coniverse/dangjang/domain/user/service/UserSignupService.java
  src/test/java/com/coniverse/dangjang/domain/user/controller/SignUpControllerTest.java
  src/test/java/com/coniverse/dangjang/fixture/UserFixture.java
Labels: refactoring, feature

#28 swagger - 403 error 해결
  src/main/java/com/coniverse/dangjang/global/config/JwtFilter.java
  src/main/java/com/coniverse/dangjang/global/config/SecurityConfig.java
Labels: bug
