Repository co-niverse/dangjang-backend, pull requests merged in 2023-09, with the labels that each got.

#30 가이드 아이디 serving 삭제, 혈당 가이드 구현
  src/main/java/com/coniverse/dangjang/domain/analysis/dto/healthMetric/BloodSugarAnalysisData.java
  src/main/java/com/coniverse/dangjang/domain/analysis/dto/healthMetric/HealthMetricAnalysisData.java
  src/main/java/com/coniverse/dangjang/domain/analysis/exception/UnitLessThanZeroException.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/document/BloodSugarGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/document/SubGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/dto/BloodSugarGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/dto/SubGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/mapper/BloodSugarGuideMapper.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/repository/BloodSugarGuideRepository.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/service/BloodSugarGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/service/BloodSugarGuideSearchService.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/document/Guide.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/dto/GuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/exception/GuideAlreadyExistsException.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/GuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/GuideService.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/document/WeightGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/mapper/WeightMapper.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/service/WeightGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/controller/HealthMetricRegisterController.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/dto/request/HealthMetricPatchRequest.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/dto/request/HealthMetricPostRequest.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/entity/HealthMetric.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/exception/SameTypeException.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricRegisterService.java
  src/main/java/com/coniverse/dangjang/global/exception/IncorrectCreatedAtException.java
  src/main/java/com/coniverse/dangjang/global/util/CreatedAtUtil.java
  src/main/java/com/coniverse/dangjang/global/validator/LocalDateValidator.java
  src/main/java/com/coniverse/dangjang/global/validator/NumberAndPositiveOrZero.java
  src/main/java/com/coniverse/dangjang/global/validator/NumberAndPositiveOrZeroValidator.java
  src/main/java/com/coniverse/dangjang/global/validator/ValidLocalDate.java
  src/main/resources/data-dev.sql
  src/main/resources/schema-dev.sql
  src/test/java/com/coniverse/dangjang/domain/guide/service/BloodSugarGuideGenerateServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/service/GuideServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/service/WeightGuideGenerateServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/controller/HealthMetricRegisterControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/mapper/HealthMetricMapperTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricRegisterServiceTest.java
  src/test/java/com/coniverse/dangjang/fixture/AnalysisDataFixture.java
  src/test/java/com/coniverse/dangjang/fixture/GuideFixture.java
  src/test/java/com/coniverse/dangjang/fixture/HealthMetricFixture.java
  src/test/resources/schema.sql
Labels: refactoring, test, feature

#33 운동 , 체중 가이드 생성 및 업데이트
  src/main/java/com/coniverse/dangjang/domain/analysis/dto/healthMetric/BloodSugarAnalysisData.java
  src/main/java/com/coniverse/dangjang/domain/analysis/dto/healthMetric/ExerciseAnalysisData.java
  src/main/java/com/coniverse/dangjang/domain/analysis/dto/healthMetric/HealthMetricAnalysisData.java
  src/main/java/com/coniverse/dangjang/domain/analysis/dto/healthMetric/WeightAnalysisData.java
  src/main/java/com/coniverse/dangjang/domain/analysis/exception/UnitLessThanZeroException.java
  src/main/java/com/coniverse/dangjang/domain/analysis/strategy/ExerciseAnalysisStrategy.java
  src/main/java/com/coniverse/dangjang/domain/analysis/strategy/WeightAnalysisStrategy.java
  src/main/java/com/coniverse/dangjang/domain/auth/controller/LoginController.java
  src/main/java/com/coniverse/dangjang/domain/auth/filter/JwtValidationFilter.java
  src/main/java/com/coniverse/dangjang/domain/code/enums/CommonCode.java
  src/main/java/com/coniverse/dangjang/domain/code/enums/GroupCode.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/document/ExerciseGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/dto/ExerciseCalorie.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/dto/ExerciseGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/dto/WalkGuideContent.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/enums/GuideString.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/mapper/ExerciseMapper.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/repository/ExerciseGuideRepository.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideSearchService.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/document/WeightGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/dto/WeightGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/mapper/WeightMapper.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/repository/WeightGuideRepository.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/service/WeightGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/service/WeightGuideSearchService.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/repository/HealthMetricRepository.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricSearchService.java
  src/test/java/com/coniverse/dangjang/domain/guide/service/ExerciseGuideGenerateServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/service/WeightGuideGenerateServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricSearchServiceTest.java
  src/test/java/com/coniverse/dangjang/fixture/AnalysisDataFixture.java
  src/test/java/com/coniverse/dangjang/fixture/GuideFixture.java
  src/test/java/com/coniverse/dangjang/fixture/HealthMetricFixture.java
Labels: feature

#38 체중 업데이트 안됨 버그 수정 및 가이드 메세지 줄바꿈
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/document/ExerciseGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/enums/GuideString.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/document/WeightGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/service/WeightGuideGenerateService.java
Labels: bug

#39 bugfix: 운동 가이드 response 필드명
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/dto/ExerciseGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/mapper/ExerciseGuideMapper.java
  src/test/java/com/coniverse/dangjang/domain/guide/exercise/controller/ExerciseGuideControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideSearchServiceTest.java
Labels: bug

#40 건강지표 차트 조회
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/document/ExerciseGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/mapper/ExerciseGuideMapper.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/repository/ExerciseGuideRepository.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideSearchService.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/controller/HealthMetricController.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/dto/response/BloodSugarMinMax.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/dto/response/HealthMetricChartData.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/dto/response/HealthMetricChartResponse.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/repository/HealthMetricRepository.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricChartSearchService.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricSearchService.java
  src/main/java/com/coniverse/dangjang/global/config/SecurityConfig.java
  src/main/java/com/coniverse/dangjang/global/util/LocalDateChangeUtil.java
  src/test/java/com/coniverse/dangjang/domain/guide/exercise/repository/ExerciseGuideRepositoryTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideGenerateServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideSearchServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/controller/HealthMetricControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/repository/HealthMetricRepositoryTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricChartSearchServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/util/LocalDateChangeUtilTest.java
  src/test/java/com/coniverse/dangjang/fixture/GuideFixture.java
  src/test/java/com/coniverse/dangjang/fixture/HealthMetricChartFixture.java
  src/test/java/com/coniverse/dangjang/fixture/HealthMetricFixture.java
  src/test/java/com/coniverse/dangjang/support/ControllerTest.java
Labels: refactoring, test, feature

#42 홈 하루 요약 가이드 조회
  src/main/java/com/coniverse/dangjang/domain/guide/common/controller/GuideController.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/dto/DayGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/DayGuideService.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/dto/ExerciseDayGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/dto/WeightDayGuide.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricChartSearchService.java
  src/test/java/com/coniverse/dangjang/domain/guide/common/controller/DayGuideControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/common/service/DayGuideServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/common/service/GuideServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricChartSearchServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/user/controller/UserControllerTest.java
  src/test/java/com/coniverse/dangjang/fixture/GuideFixture.java
  src/test/java/com/coniverse/dangjang/support/ControllerTest.java
Labels: feature
