Repository co-niverse/dangjang-backend, pull requests merged in 2023-10, with the labels that each got.

#50 log event 누락 부분 추가
  src/main/java/com/coniverse/dangjang/domain/log/enums/Event.java
Labels: bug

#55 Redis Container 연결 오류 해결
  src/main/java/com/coniverse/dangjang/global/config/RedisConfig.java
Labels: bug

#58 WeightGuide MongoTemplate로 수정
  src/main/java/com/coniverse/dangjang/domain/guide/weight/service/WeightGuideGenerateService.java
Labels: refactoring

#59 건강지표 마지막 생성일 조회 api 생성/ 닉네임 조건 수정 / 헬스커넥트 연동 여부 수정
  src/main/java/com/coniverse/dangjang/domain/auth/service/DefaultOauthLoginService.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/controller/HealthMetricController.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/dto/HealthMetricLastDateResponse.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/enums/HealthConnect.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/repository/HealthMetricRepository.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricSearchService.java
  src/main/java/com/coniverse/dangjang/domain/user/controller/UserController.java
  src/main/java/com/coniverse/dangjang/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/coniverse/dangjang/domain/user/repository/UserRepository.java
  src/main/java/com/coniverse/dangjang/domain/user/service/UserSearchService.java
  src/main/java/com/coniverse/dangjang/domain/user/service/UserSignupService.java
  src/test/java/com/coniverse/dangjang/domain/auth/service/OauthLoginServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/controller/HealthConnectControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/controller/HealthMetricControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricSearchServiceTest.java
  src/test/java/com/coniverse/dangjang/support/ControllerTest.java
Labels: refactoring, feature

#62 UserLog 추가
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/dto/SubGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/service/BloodSugarGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/controller/GuideController.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/dto/response/DayGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/dto/response/GuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/DayGuideService.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/GuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/GuideService.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/dto/ExerciseGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/dto/WeightDayGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/dto/WeightGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/service/WeightGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/dto/response/HealthMetricResponse.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/mapper/HealthMetricMapper.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricRegisterService.java
  src/main/java/com/coniverse/dangjang/domain/log/dto/request/UserLog.java
  src/main/java/com/coniverse/dangjang/domain/user/entity/User.java
  src/test/java/com/coniverse/dangjang/domain/guide/common/controller/DayGuideControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/common/service/DayGuideServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/mapper/HealthMetricMapperTest.java
  src/test/java/com/coniverse/dangjang/domain/point/service/PointHistoryServiceTest.java
  src/test/java/com/coniverse/dangjang/fixture/GuideFixture.java
Labels: refactoring

#63 포인트 적립 방법 목록 조회 추가 & 금액권 수정
  src/main/java/com/coniverse/dangjang/domain/point/dto/response/ProductListResponse.java
  src/main/java/com/coniverse/dangjang/domain/point/entity/PointProduct.java
  src/main/java/com/coniverse/dangjang/domain/point/service/PointService.java
  src/main/resources/data-dev.sql
  src/main/resources/schema-dev.sql
  src/test/java/com/coniverse/dangjang/domain/point/controller/PointHistoryControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/point/service/PointHistoryServiceTest.java
  src/test/java/com/coniverse/dangjang/fixture/PointFixture.java
  src/test/resources/schema.sql
Labels: refactoring, feature

#64 로그 스펙 변경
  src/main/java/com/coniverse/dangjang/domain/guide/common/dto/response/DayGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/DayGuideService.java
  src/main/java/com/coniverse/dangjang/domain/log/controller/AppLogController.java
  src/main/java/com/coniverse/dangjang/domain/log/dto/app/AppLog.java
  src/main/java/com/coniverse/dangjang/domain/log/dto/request/LogRequest.java
  src/main/java/com/coniverse/dangjang/domain/log/dto/request/UserLog.java
  src/main/java/com/coniverse/dangjang/domain/log/enums/Event.java
  src/main/java/com/coniverse/dangjang/domain/log/mapper/LogMapper.java
  src/main/java/com/coniverse/dangjang/domain/log/service/LogService.java
  src/main/java/com/coniverse/dangjang/domain/user/dto/response/UserDiabeticResponse.java
  src/main/java/com/coniverse/dangjang/global/config/SecurityConfig.java
  src/test/java/com/coniverse/dangjang/domain/log/controller/AppLogControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/log/mapper/LogMapperTest.java
  src/test/java/com/coniverse/dangjang/domain/log/service/LogServiceTest.java
  src/test/java/com/coniverse/dangjang/fixture/GuideFixture.java
  src/test/java/com/coniverse/dangjang/fixture/LogFixture.java
  src/test/java/com/coniverse/dangjang/fixture/UserFixture.java
Labels: feature

#65 포인트 상품 구매 response 및 request 수정 & notification_seq 버그 수정
  src/main/java/com/coniverse/dangjang/domain/notification/entity/Notification.java
  src/main/java/com/coniverse/dangjang/domain/point/controller/PointController.java
  src/main/java/com/coniverse/dangjang/domain/point/dto/request/UsePointRequest.java
  src/main/java/com/coniverse/dangjang/domain/point/dto/response/UsePointResponse.java
  src/main/java/com/coniverse/dangjang/domain/point/entity/PurchaseHistory.java
  src/main/java/com/coniverse/dangjang/domain/point/mapper/PointMapper.java
  src/main/java/com/coniverse/dangjang/domain/point/service/PointService.java
  src/main/resources/schema-dev.sql
  src/test/java/com/coniverse/dangjang/domain/point/controller/PointHistoryControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/point/service/PointHistoryServiceTest.java
  src/test/java/com/coniverse/dangjang/fixture/PointFixture.java
  src/test/resources/schema.sql
Labels: bug, refactoring

#67 v1.1.1 릴리즈
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/dto/SubGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/service/BloodSugarGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/controller/GuideController.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/dto/response/DayGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/dto/response/GuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/DayGuideService.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/GuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/GuideService.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/dto/ExerciseGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/dto/WeightDayGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/dto/WeightGuideResponse.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/service/WeightGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/dto/response/HealthMetricResponse.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/mapper/HealthMetricMapper.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricRegisterService.java
  src/main/java/com/coniverse/dangjang/domain/intro/dto/Version.java
  src/main/java/com/coniverse/dangjang/domain/log/controller/AppLogController.java
  src/main/java/com/coniverse/dangjang/domain/log/dto/app/AppLog.java
  src/main/java/com/coniverse/dangjang/domain/log/dto/request/LogRequest.java
  src/main/java/com/coniverse/dangjang/domain/log/enums/Event.java
  src/main/java/com/coniverse/dangjang/domain/log/mapper/LogMapper.java
  src/main/java/com/coniverse/dangjang/domain/log/service/LogService.java
  src/main/java/com/coniverse/dangjang/domain/notification/entity/Notification.java
  src/main/java/com/coniverse/dangjang/domain/point/controller/PointController.java
  src/main/java/com/coniverse/dangjang/domain/point/dto/request/UsePointRequest.java
  src/main/java/com/coniverse/dangjang/domain/point/dto/response/ProductListResponse.java
  src/main/java/com/coniverse/dangjang/domain/point/dto/response/UsePointResponse.java
  src/main/java/com/coniverse/dangjang/domain/point/entity/PointProduct.java
  src/main/java/com/coniverse/dangjang/domain/point/entity/PurchaseHistory.java
  src/main/java/com/coniverse/dangjang/domain/point/mapper/PointMapper.java
  src/main/java/com/coniverse/dangjang/domain/point/service/PointService.java
  src/main/java/com/coniverse/dangjang/domain/user/dto/response/UserDiabeticResponse.java
  src/main/java/com/coniverse/dangjang/domain/user/entity/User.java
  src/main/java/com/coniverse/dangjang/global/config/SecurityConfig.java
  src/main/resources/data-dev.sql
  src/main/resources/schema-dev.sql
  src/test/java/com/coniverse/dangjang/domain/guide/common/controller/DayGuideControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/common/service/DayGuideServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/mapper/HealthMetricMapperTest.java
  src/test/java/com/coniverse/dangjang/domain/log/controller/AppLogControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/log/mapper/LogMapperTest.java
  src/test/java/com/coniverse/dangjang/domain/log/service/LogServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/point/controller/PointHistoryControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/point/service/PointHistoryServiceTest.java
  src/test/java/com/coniverse/dangjang/fixture/GuideFixture.java
  src/test/java/com/coniverse/dangjang/fixture/LogFixture.java
  src/test/java/com/coniverse/dangjang/fixture/PointFixture.java
  src/test/java/com/coniverse/dangjang/fixture/UserFixture.java
  src/test/resources/schema.sql
Labels: release

#69 v1.1.2 릴리즈
  build.gradle
  src/main/java/com/coniverse/dangjang/domain/intro/dto/Version.java
  src/main/java/com/coniverse/dangjang/domain/scheduler/service/SchedulerService.java
  src/main/java/com/coniverse/dangjang/global/config/SchedulerConfiguration.java
  src/main/resources/schema-dev.sql
  src/test/resources/schema.sql
Labels: bug, release

#70 앱 버전 업데이트
  src/main/java/com/coniverse/dangjang/domain/intro/dto/Version.java
Labels: release

#71 app 버전 업데이트
  src/main/java/com/coniverse/dangjang/domain/intro/dto/Version.java
Labels: release

#73 건강지표 삭제 기능 구현
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/document/BloodSugarGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/bloodsugar/service/BloodSugarGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/GuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/common/service/GuideService.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/document/ExerciseGuide.java
  src/main/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/guide/weight/service/WeightGuideGenerateService.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/controller/HealthMetricController.java
  src/main/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricRegisterService.java
  src/test/java/com/coniverse/dangjang/domain/guide/bloodsugar/service/BloodSugarGuideGenerateServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/exercise/service/ExerciseGuideGenerateServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/guide/weight/service/WeightGuideGenerateServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/controller/HealthMetricControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/healthmetric/service/HealthMetricRegisterServiceTest.java
  src/test/java/com/coniverse/dangjang/fixture/GuideFixture.java
  src/test/java/com/coniverse/dangjang/support/SimpleMockMvc.java
Labels: refactoring, test, feature

#74 fcmToken 등록 및 업데이트 api 구현
  src/main/java/com/coniverse/dangjang/domain/auth/controller/LoginController.java
  src/main/java/com/coniverse/dangjang/domain/auth/dto/request/LogoutFcmTokenRequest.java
  src/main/java/com/coniverse/dangjang/domain/auth/service/DefaultOauthLoginService.java
  src/main/java/com/coniverse/dangjang/domain/auth/service/OauthLoginService.java
  src/main/java/com/coniverse/dangjang/domain/notification/entity/FcmId.java
  src/main/java/com/coniverse/dangjang/domain/notification/entity/UserFcmToken.java
  src/main/java/com/coniverse/dangjang/domain/notification/mapper/NotificationMapper.java
  src/main/java/com/coniverse/dangjang/domain/notification/repository/UserFcmTokenRepository.java
  src/main/java/com/coniverse/dangjang/domain/notification/service/NotificationService.java
  src/main/java/com/coniverse/dangjang/domain/user/controller/SignupController.java
  src/main/java/com/coniverse/dangjang/domain/user/controller/UserController.java
  src/main/java/com/coniverse/dangjang/domain/user/dto/request/PostFcmTokenRequest.java
  src/main/java/com/coniverse/dangjang/domain/user/service/UserSignupService.java
  src/main/resources/data-dev.sql
  src/main/resources/schema-dev.sql
  src/test/java/com/coniverse/dangjang/domain/auth/controller/LoginControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/auth/service/OauthLoginServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/scheduler/service/SchedulerServiceTest.java
  src/test/java/com/coniverse/dangjang/domain/user/controller/SignupControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/user/controller/UserControllerTest.java
  src/test/java/com/coniverse/dangjang/domain/user/service/UserSignupServiceTest.java
  src/test/java/com/coniverse/dangjang/fixture/NotificationFixture.java
Labels: feature
